force-app/main/default/objects/BoatType__c/fields/Boat__c.field-meta.xml
<CustomField>
    <fullName>Boat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Boat</label>
    <referenceTo>Boat__c</referenceTo>
    <relationshipLabel>Boat Types</relationshipLabel>
    <relationshipName>Boat_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BoatHelper.cls
public class BoatHelper {
    public static void createBoats(List<Boat__c> btlist)
    {
        Set<Id> btId = new Set<Id>();
        for(Boat__c bt:btlist)
        {
            btId.add(bt.Id);
        }
        
        List<Boat__c> boatlist = [Select Id,BoatType__c from Boat__c where BoatType__c IN : btId];
        for(Boat__c btype :boatlist)
        {
            btype.BoatType__c = btype.Id; 
        }
        update boatlist;
        
    }

}